In [72]:
import numpy as np

import train samples

In [73]:
train_irises = np.load('irises.npy')
train_irises.shape

(120, 4)

In [74]:
train_types = np.load('types.npy')
train_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

import test samples

In [75]:
test_irises = np.load('new_irises.npy')
test_irises

array([[5. , 3.6, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.3, 1.4, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.2, 2.7, 3.9, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.4, 3. , 4.5, 1.5],
       [5.5, 2.5, 4. , 1.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.5, 3. , 5.8, 2.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 5. , 1.5],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [6.1, 2.6, 5.6, 1.4],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [5.9, 3. , 5.1, 1.8]])

K-N-N algorithm

In [82]:
from scipy import stats
# calculate Euclidean distance within each test and train sample using vectorized operations and reshaping
answers = np.sqrt(np.sum(np.square(np.subtract(train_irises.reshape(1,120,4) , test_irises.reshape(30,1,4))),axis = 2))
# find k nearest neighbors ( index of k minimum Euclidean distances for each test sample)
k = 5
answers = np.argsort(answers)[: , :k]
# find type of k nearest neighbors for each test sample
answers = train_types[answers]
# find most frequent type in k nearest neighbors for each test sample
answers = stats.mode(answers , axis = 1)[0]
answers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2])

type of samples ecording to dataset

In [76]:
test_types = np.load("new_types.npy")
test_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])